"""Initial migration

Revision ID: 46da05aeb666
Revises: 
Create Date: 2025-05-27 06:58:17.615169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46da05aeb666'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenantId', sa.Integer(), nullable=False),
    sa.Column('Type', sa.Enum('WHOLESALER', 'DEALER', name='businesstypeenum'), nullable=False),
    sa.Column('SubType', sa.String(length=100), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('AddressLine1', sa.String(length=255), nullable=True),
    sa.Column('AddressLine2', sa.String(length=255), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('StartDateTime', sa.DateTime(), nullable=True),
    sa.Column('EndDateTime', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['TenantId'], ['tenants.TenantId'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('tenants',
    sa.Column('TenantId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenantName', sa.String(length=255), nullable=False),
    sa.Column('TenantDescription', sa.Text(), nullable=True),
    sa.Column('TenantStatus', sa.String(length=50), nullable=False),
    sa.Column('TenantStartDateTime', sa.DateTime(), nullable=True),
    sa.Column('TenantEndDateTime', sa.DateTime(), nullable=True),
    sa.Column('TenantType', sa.String(length=100), nullable=True),
    sa.Column('TenantSubType', sa.String(length=100), nullable=True),
    sa.Column('AdditionalData', sa.JSON(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('TenantId')
    )
    op.create_table('users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenantId', sa.Integer(), nullable=False),
    sa.Column('BusinessId', sa.Integer(), nullable=True),
    sa.Column('Role', sa.Enum('SuperAdmin', 'TechAdmin', 'SalesAdmin', 'WholesalerAdmin', 'Wholesaler', 'DealerAdmin', 'Dealer', name='userroleenum'), nullable=False),
    sa.Column('UserName', sa.String(length=100), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('AddressLine1', sa.String(length=255), nullable=True),
    sa.Column('AddressLine2', sa.String(length=255), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('UserStatus', sa.Enum('Active', 'Inactive', name='userstatusenum'), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BusinessId'], ['businesses.Id'], ),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['TenantId'], ['tenants.TenantId'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('UserName')
    )
    op.create_table('configurations',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('SubType', sa.String(length=100), nullable=True),
    sa.Column('RefId', sa.String(length=255), nullable=False),
    sa.Column('Key', sa.String(length=255), nullable=False),
    sa.Column('Value', sa.Text(), nullable=False),
    sa.Column('ValueType', sa.String(length=20), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('features',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('SubType', sa.String(length=100), nullable=True),
    sa.Column('FeatureName', sa.String(length=255), nullable=False),
    sa.Column('FeatureDescription', sa.Text(), nullable=True),
    sa.Column('FeatureKey', sa.String(length=100), nullable=False),
    sa.Column('FeatureValue', sa.String(length=255), nullable=False),
    sa.Column('ValueType', sa.String(length=20), nullable=False),
    sa.Column('StartDateTime', sa.DateTime(), nullable=True),
    sa.Column('EndDateTime', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('FeatureKey')
    )
    op.create_table('orders',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenantId', sa.Integer(), nullable=False),
    sa.Column('BusinessId', sa.Integer(), nullable=False),
    sa.Column('Type', sa.Enum('Booked', 'Requested', name='ordertypeenum'), nullable=False),
    sa.Column('SubType', sa.String(length=100), nullable=True),
    sa.Column('OrderStatus', sa.Enum('New', 'InProgress', 'Done', 'Cancelled', name='orderstatusenum'), nullable=False),
    sa.Column('OrderDateTime', sa.DateTime(), nullable=False),
    sa.Column('AdditionalData', sa.JSON(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BusinessId'], ['businesses.Id'], ),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['TenantId'], ['tenants.TenantId'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('products',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProductId', sa.String(length=100), nullable=False),
    sa.Column('TenantId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('MRP', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('DiscountType', sa.Enum('Fixed', 'Percentage', name='discounttypeenum'), nullable=True),
    sa.Column('DiscountAmount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('TaxType', sa.String(length=50), nullable=True),
    sa.Column('TaxAmount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ImageLink', sa.String(length=1024), nullable=True),
    sa.Column('AdditionalData', sa.JSON(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['TenantId'], ['tenants.TenantId'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('subscriptions',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('RefId', sa.String(length=255), nullable=False),
    sa.Column('SubType', sa.String(length=100), nullable=True),
    sa.Column('StartDateTime', sa.DateTime(), nullable=False),
    sa.Column('EndDateTime', sa.DateTime(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ordered_products',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderId', sa.Integer(), nullable=False),
    sa.Column('ProductId', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('DiscountType', sa.Enum('Fixed', 'Percentage', name='discounttypeenum'), nullable=True),
    sa.Column('DiscountAmount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('TaxType', sa.String(length=50), nullable=True),
    sa.Column('TaxAmount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('TotalCost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['OrderId'], ['orders.Id'], ),
    sa.ForeignKeyConstraint(['ProductId'], ['products.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordered_products')
    op.drop_table('subscriptions')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('features')
    op.drop_table('configurations')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('businesses')
    # ### end Alembic commands ###
