name: Database Migration

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'alembic/versions/*.py'
      - 'backend/models.py'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  INSTANCE_NAME: inventory-mysql-prod
  DATABASE_NAME: inventory_mgmt
  REGION: us-central1

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Database Migrations
      run: |
        # Set up Cloud SQL Proxy
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        
        # Start Cloud SQL Proxy in background
        ./cloud_sql_proxy -instances=$PROJECT_ID:$REGION:$INSTANCE_NAME=tcp:3306 &
        sleep 10
        
        # Set database URL for migrations
        export DB_HOST=127.0.0.1
        export DB_PORT=3306
        export DB_USER=${{ secrets.DB_USER }}
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        export DB_NAME=${{ secrets.DB_NAME }}
        
        # Run Alembic migrations
        alembic upgrade head
        
        # Stop Cloud SQL Proxy
        pkill cloud_sql_proxy
